<?php

namespace Esprit\CollaborateurBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CollaborateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CollaborateurRepository extends EntityRepository
{
}
