parameters:
#    esprit_admin.example.class: Esprit\AdminBundle\Example

services:
#    esprit_admin.example:
#        class: %esprit_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
