<?php

namespace Esprit\MangerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MangerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MangerRepository extends EntityRepository
{
}
