parameters:
#    esprit_client.example.class: Esprit\ClientBundle\Example

services:
#    esprit_client.example:
#        class: %esprit_client.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
