<?php

namespace Esprit\MangerBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class MangerController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Esprit\MangerBundle\Controller\MangerController();
        return $instance;
    }
}
