<?php

namespace Esprit\CollaborateurBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class CollaborateurController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Esprit\CollaborateurBundle\Controller\CollaborateurController();
        return $instance;
    }
}
