<?php

namespace Esprit\ClientBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ClientController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Esprit\ClientBundle\Controller\ClientController();
        return $instance;
    }
}
