# src/Esprit/MangerBundle/Resources/config/routing.yml
 
espritmanager_accueil:
    pattern: /acceuil
    defaults: { _controller: EspritMangerBundle:Manger:index }
espritmanager_voir: 
    pattern: /manager/{id}
    defaults:  { _controller: EspritMangerBundle:Manger:voir }
espritmanager_ajouter: 
    pattern: /ajouter
    defaults:  { _controller: EspritMangerBundle:Manger:ajouter }  
espritmanager_modifier:
    pattern: /modifier/{id}
    defaults:  { _controller: EspritMangerBundle:Manger:modifier }
    requirements:
        id:  \d+        
espritmanager_supprimer:
    pattern: /supprimer/{id}
    defaults:  { _controller: EspritMangerBundle:Manger:supprimer }
    requirements:
        id:  \d+ 
        

