parameters:
#    esprit_collaborateur.example.class: Esprit\CollaborateurBundle\Example

services:
#    esprit_collaborateur.example:
#        class: %esprit_collaborateur.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
